# Generated by Django 4.1.3 on 2023-04-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='categorie',
            field=models.IntegerField(default=None),
        ),
    ]
