# Generated by Django 4.1.3 on 2023-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employer_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='direction',
            field=models.CharField(choices=[('DT', 'DT'), ('DTE', 'DTE'), ('PAC', 'PAC'), ('DAF', 'DAF')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='categorie',
            field=models.CharField(choices=[('admin', 'admin'), ('directeur', 'directeur'), ('chef labo', 'chef labo'), ('operateur', 'operateur'), ('reception', 'reception')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
