# Generated by Django 4.1.3 on 2023-04-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employer_direction_alter_employer_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='categorie',
            field=models.CharField(choices=[('admin', 'admin'), ('directeur', 'directeur'), ('chef labo', 'chef labo'), ('operateur', 'operateur'), ('reception', 'reception')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employer',
            name='direction',
            field=models.CharField(choices=[('DT', 'DT'), ('DTE', 'DTE'), ('PAC', 'PAC'), ('DAF', 'DAF')], max_length=50, null=True),
        ),
    ]
