# Generated by Django 4.1.3 on 2023-04-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_employer_categorie_alter_employer_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='direction',
        ),
    ]
