# Generated by Django 4.1.3 on 2023-04-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employer_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='materiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('carton', 'catron'), ('verre', 'verre'), ('type 3', 'type 3'), ('type 4', 'type 4'), ('type 5', 'type 5')], max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=10)),
                ('delai', models.IntegerField()),
            ],
        ),
    ]
