# Generated by Django 4.1.3 on 2023-04-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_materiaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaux',
            name='suffix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
