# Generated by Django 4.1.3 on 2023-04-12 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_materiaux_suffix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.AddField(
            model_name='employer',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='mail', max_length=70),
        ),
        migrations.AddField(
            model_name='employer',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='leave_days_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
