# Generated by Django 4.1.3 on 2023-04-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_employer_user_employer_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
