# Generated by Django 4.1.3 on 2023-04-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_employer_leave_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
    ]
