# Generated by Django 4.1.3 on 2023-04-12 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_remove_employer_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='categorie',
            field=models.CharField(choices=[('admin', 'admin'), ('directeur', 'directeur'), ('chef labo', 'chef labo'), ('operateur', 'operateur'), ('reception', 'reception')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employer',
            name='direction',
            field=models.CharField(choices=[('DT', 'DT'), ('DTE', 'DTE'), ('PAC', 'PAC'), ('DAF', 'DAF')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
