# Generated by Django 4.1.3 on 2023-04-12 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_employer_categorie_employer_date_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('leave_days', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(choices=[('admin', 'admin'), ('directeur', 'directeur'), ('chef labo', 'chef labo'), ('operateur', 'operateur'), ('reception', 'reception')], default=None, max_length=100)),
                ('direction', models.CharField(choices=[('DT', 'DT'), ('DTE', 'DTE'), ('PAC', 'PAC'), ('DAF', 'DAF')], max_length=50, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='employer',
        ),
    ]
