# Generated by Django 4.1.3 on 2023-04-12 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_employeur_delete_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeur',
            name='user',
        ),
        migrations.AddField(
            model_name='employeur',
            name='uuser',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
