# Generated by Django 4.1.3 on 2023-04-12 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_remove_employeur_user_employeur_uuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeur',
            name='uuser',
        ),
        migrations.AddField(
            model_name='employeur',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
