# Generated by Django 4.2 on 2023-04-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_employer_delete_employeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField()),
                ('last_day', models.DateField()),
                ('occasion', models.CharField(max_length=150)),
            ],
        ),
    ]
