# Generated by Django 4.2 on 2023-04-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='days_number',
            field=models.IntegerField(default=0),
        ),
    ]
