# Generated by Django 4.2 on 2023-04-22 12:59

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_employer_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='weekends',
            field=app.models.ListField(default=[]),
        ),
    ]
