# Generated by Django 4.2 on 2023-04-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
